#!/bin/bash
#SBATCH -J boosting
#SBATCH -o /home/jdc396/slurm/logs/%j.out
#SBATCH -e /home/jdc396/slurm/logs/%j.err
#SBATCH -N 1
#SBATCH -n 2
#SBATCH --mem=30G
#SBATCH -t 48:00:00
#SBATCH --partition=default_partition

source /share/apps/anaconda3/2020.11/etc/profile.d/conda.sh
conda activate milov2
cd /home/jdc396/Ranking-IL
python train.py experiment=dac_baseline agent=dac algo=sac expert_dir=/home/jdc396/Ranking-IL/expert_sac/ agent.disc_type=sa
    
